################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/HAL_Driver/Src/stm32f4xx_hal.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_adc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_can.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_cec.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_cortex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_crc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_cryp.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_cryp_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_dac.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_dac_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_dcmi.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_dfsdm.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_dma.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_dma2d.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_dsi.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_eth.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_flash.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_fmpi2c.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_gpio.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_hash.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_hash_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_hcd.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_i2c.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_i2s.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_i2s_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_irda.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_iwdg.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_lptim.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_ltdc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_mmc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_nand.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_nor.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_pccard.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_pcd.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_pwr.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_qspi.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_rcc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_rng.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_rtc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_sai.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_sai_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_sd.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_sdram.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_smartcard.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_spdifrx.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_spi.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_sram.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_tim.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_uart.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_usart.c \
../Drivers/HAL_Driver/Src/stm32f4xx_hal_wwdg.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_adc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_crc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_dac.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_dma.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_dma2d.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_exti.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_fmc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_fsmc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_gpio.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_i2c.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_lptim.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_pwr.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_rcc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_rng.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_rtc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_sdmmc.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_spi.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_tim.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_usart.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_usb.c \
../Drivers/HAL_Driver/Src/stm32f4xx_ll_utils.c 

OBJS += \
./Drivers/HAL_Driver/Src/stm32f4xx_hal.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_adc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_adc_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_can.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_cec.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_cortex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_crc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_cryp.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_cryp_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dac.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dac_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dcmi.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dfsdm.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dma.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dma2d.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dma_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dsi.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_eth.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_flash.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_flash_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_fmpi2c.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_gpio.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_hash.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_hash_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_hcd.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_i2c.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_i2c_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_i2s.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_i2s_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_irda.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_iwdg.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_lptim.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_ltdc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_mmc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_nand.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_nor.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pccard.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pcd.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pcd_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pwr.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pwr_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_qspi.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rcc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rcc_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rng.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rtc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rtc_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sai.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sai_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sd.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sdram.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_smartcard.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_spdifrx.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_spi.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sram.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_tim.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_tim_ex.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_uart.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_usart.o \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_wwdg.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_adc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_crc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_dac.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_dma.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_dma2d.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_exti.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_fmc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_fsmc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_gpio.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_i2c.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_lptim.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_pwr.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_rcc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_rng.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_rtc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_sdmmc.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_spi.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_tim.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_usart.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_usb.o \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_utils.o 

C_DEPS += \
./Drivers/HAL_Driver/Src/stm32f4xx_hal.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_adc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_adc_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_can.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_cec.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_cortex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_crc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_cryp.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_cryp_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dac.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dac_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dcmi.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dcmi_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dfsdm.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dma.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dma2d.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dma_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_dsi.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_eth.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_flash.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_flash_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_fmpi2c.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_fmpi2c_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_gpio.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_hash.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_hash_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_hcd.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_i2c.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_i2c_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_i2s.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_i2s_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_irda.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_iwdg.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_lptim.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_ltdc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_ltdc_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_mmc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_nand.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_nor.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pccard.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pcd.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pcd_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pwr.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_pwr_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_qspi.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rcc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rcc_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rng.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rtc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_rtc_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sai.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sai_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sd.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sdram.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_smartcard.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_spdifrx.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_spi.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_sram.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_tim.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_tim_ex.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_uart.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_usart.d \
./Drivers/HAL_Driver/Src/stm32f4xx_hal_wwdg.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_adc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_crc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_dac.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_dma.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_dma2d.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_exti.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_fmc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_fsmc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_gpio.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_i2c.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_lptim.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_pwr.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_rcc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_rng.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_rtc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_sdmmc.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_spi.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_tim.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_usart.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_usb.d \
./Drivers/HAL_Driver/Src/stm32f4xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/HAL_Driver/Src/%.o: ../Drivers/HAL_Driver/Src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F429xx -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Inc" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Drivers/BSP/STM32F429I-Discovery" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Drivers/HAL_Driver/Inc" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Drivers/HAL_Driver/Inc/Legacy" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Drivers/BSP/Components" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Middlewares/Third_Party/FatFs/src/drivers" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Middlewares/ST/STM32_USB_Host_Library/Core/Inc" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Middlewares/ST/STM32_USB_Host_Library/Class/MSC/Inc" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Middlewares/Third_Party/FatFs/src" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/gacevedo/Documents/github/USB_POT_FREERTOS/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


